{{- if .Values.tls.mutual.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata: { name: {{ include "datomic-scylla.fullname" . }}-ca-issuer, namespace: {{ .Values.namespace }} }
spec: { ca: { secretName: {{ .Values.scylla.clusterName }}-local-client-ca } }
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: { name: {{ include "datomic-scylla.fullname" . }}-client, namespace: {{ .Values.namespace }} }
spec:
  secretName: {{ include "datomic-scylla.fullname" . }}-client-tls
  commonName: {{ .Values.auth.appUser }}
  usages: [ "client auth", "digital signature", "key encipherment" ]
  issuerRef: { name: {{ include "datomic-scylla.fullname" . }}-ca-issuer, kind: Issuer }
  keystores:
    pkcs12:
      create: true
      # Note: The Modern2023 profile requires cert-manager v1.14+
      profile: Modern2023
      passwordSecretRef: { name: {{ include "datomic-scylla.secretName" . }}, key: keystore-password }
{{- end }}
