{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datomic-scylla.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels: {{- include "datomic-scylla.labels" . | nindent 4 }}
type: Opaque
stringData:
  app-password: {{ .Values.secrets.appPassword | quote }}
  superuser-password: {{ .Values.secrets.superuserPassword | quote }}
  superuser-bootstrap-password: {{ .Values.secrets.superuserBootstrapPassword | quote }}
  truststore-password: {{ .Values.secrets.truststorePassword | quote }}
  keystore-password: {{ .Values.secrets.keystorePassword | quote }}
{{- end }}
