{{- if not .Values.secrets.existingSecret }}
{{- if eq .Values.secrets.appPassword "change-me-app-password" }}
{{- fail "A custom secrets.appPassword is required (or set secrets.existingSecret) for production safety." }}
{{- end }}
{{- if eq .Values.secrets.superuserPassword "change-me-scylla-superuser" }}
{{- fail "A custom secrets.superuserPassword is required (or set secrets.existingSecret) for production safety." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datomic-scylla.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels: {{- include "datomic-scylla.labels" . | nindent 4 }}
type: Opaque
stringData:
  app-password: {{ .Values.secrets.appPassword | quote }}
  superuser-password: {{ .Values.secrets.superuserPassword | quote }}
  superuser-bootstrap-password: {{ .Values.secrets.superuserBootstrapPassword | quote }}
  truststore-password: {{ .Values.secrets.truststorePassword | quote }}
  keystore-password: {{ .Values.secrets.keystorePassword | quote }}
{{- end }}
